replicaCount: 2
nameOverride: "teste"
image:
  repository: rmiguel/argocd-pr-env
  tag: "57-1f22c13a8652e50dc5aa8270f5f026f3ffc8a548"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: env-temp-v3.local.io
      paths:
        - path: /api/v1
          pathType: Prefix
  tls: []
