replicaCount: 2
nameOverride: "teste"
image:
  repository: rmiguel/argocd-pr-env
  tag: "52-65b2c8201df5d01caa49e216105ea7ca6d1cad58"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: $HOST
      paths:
        - path: /
          pathType: Prefix
  tls: []
