replicaCount: 2
nameOverride: "teste"
image:
  repository: rmiguel/argocd-pr-env
  tag: "63-868cfb9750e7b1b0aec56fb61929fc42c25ed84d"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: env-temp-v3.local.io
      paths:
        - path: /api/v1
          pathType: Prefix
  tls: []
