replicaCount: 2
nameOverride: "teste"
image:
  repository: rmiguel/argocd-pr-env
  tag: "51-d3e5e687cfd0e3ee62851138cac48f5d37f44e18"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: $HOST
      paths:
        - path: /
          pathType: Prefix
  tls: []
