replicaCount: 2
nameOverride: "teste"
image:
  repository: rmiguel/argocd-pr-env
  tag: "53-430e7cf72dab5483607c066710d9091cecadc514"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: $HOST
      paths:
        - path: /
          pathType: Prefix
  tls: []
