replicaCount: 2
nameOverride: "teste"
image:
  repository: rmiguel/argocd-pr-env
  tag: "54-8273ae9649fd7f2e0b23022f772c95e994853efb"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: ephv-v5.local.io
      paths:
        - path: /
          pathType: Prefix
  tls: []
