replicaCount: 2
nameOverride: "teste"
image:
  repository: rmiguel/argocd-pr-env
  tag: "49-aacf7b6f10618c8bfff93f36b32b3ba3aa66941b"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: teste.local.io
      paths:
        - path: /api/v1
          pathType: Prefix
  tls: []
