replicaCount: 2
nameOverride: "teste"
image:
  repository: rmiguel/argocd-pr-env
  tag: "50-78629dedbb1fc4767394fa578bb7e5a9d70a68d2"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: $HOST
      paths:
        - path: /
          pathType: Prefix
  tls: []
