replicaCount: 2
nameOverride: "teste"
image:
  repository: rmiguel/argocd-pr-env
  tag: "78-cd5192f0c766791e3e4553cec692633b8526676b"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: env-temp-3.local.io
      paths:
        - path: /api/v1
          pathType: Prefix
  tls: []
