replicaCount: 2
nameOverride: "teste"
image:
  repository: rmiguel/argocd-pr-env
  tag: "56-c671007f831c8aa229aa031e1685c5f4dd087b66"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: env-temp-v2.local.io
      paths:
        - path: /api/v1
          pathType: Prefix
  tls: []
