replicaCount: 2
nameOverride: "teste"
image:
  repository: rmiguel/argocd-pr-env
  tag: "73-5c439b12fa72cdc357320cdbcd9e40c91af9584a"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: env-temp-1.local.io
      paths:
        - path: /api/v1
          pathType: Prefix
  tls: []
